### ISSUE TITLE
[QUESTION] is the legacy global _auth setting not supported?

### ISSUE THREAD

**Issue by ryhinchey** [npm/npm-registry-fetch#47]
# What / Why
The Nexus Sonatype registry uses a global `_auth` field in the `.npmrc` file.  Prior to version `10.0.0`,  this package worked with that setting.  After `10.0.0`, I get 401 errors when trying to authenticate with the Nexus registry.  `v10` of this package was brought in through [libnpmaccess@4.0.2](https://github.com/npm/libnpmaccess).

I see `opts._auth` is [deprecated](https://github.com/npm/npm-registry-fetch#-opts_auth); however, I'd expect it still to work with a warning.

**Comment by isaacs** [comment]
This should work again with the latest update to the npm cli.

In short, no, the global `_auth` setting _passed to npm-registry-fetch_ is no longer supported, by design.  However, the config loading logic in npm will now read that top-level `_auth` and scope it to the current registry, so that npm-registry-fetch _will_ send it to the correct locations.

We had updated the npm config settings to scope a top-level auth param when saving the config file, but not when loading it, which is how this escaped notice.  Apologies for the inconvenience.
