### ISSUE TITLE
[BUG] URL is not defined

### ISSUE THREAD

**Issue by natewernimont-wk** [npm/npm-registry-fetch#49]
# What / Why
On a legacy system, when fetching dependencies, we get the following error:
> ERR! URL is not defined

This started as of npm v7.11.0, which consumes [this](https://github.com/npm/npm-registry-fetch/commit/cc11cc15c9f457c01159a69ce342dc99dea12456) change. [This](https://stackoverflow.com/questions/52566578/url-is-not-defined-in-node-js) StackOverflow question recommends adding this explicit line in order to resolve the issue.

> var URL = require('url').URL;

I am also not a frequent user of NPM, and I am touching a legacy system. It is very likely that another fix would be more appropriate :).

## When
As of npm v7.11.0, which consumes the commit linked above.

## Where
npm public registry - this specifically occurs when consuming jspm.

## How
Executing `npm install -g jspm@0.16.55` on npm v7.11.0+.

### Current Behavior
It errors, saying `URL is not defined`.

### Steps to Reproduce
Pull npm v7.11.0.
Run `npm install -g jspm@0.16.55`.

### Expected Behavior
I expect pulling the dependency to work.

## Who
N/A

## References
N/A

**Comment by nlf** [comment]
while i don't really object to adding this, since it's a pretty trivial change with no real consequences, i would point out that this module (and npm 7 in general) only support node versions >=10.0.0 which is when the `URL` global was added, so all _supported_ versions of node as of today work correctly.

if you're stuck on node < 10 i would stick with npm@6 to play it safe since we have not done any amount of testing to have any idea what might be broken

**Comment by evantahler** [comment]
I can see this bug on node v15.14.0 as of recently
